Implementa funções especiais
DesignLiquido/FolEs pull request #118
Opened 2024-04-01 14:35 UTC by VitBrandao

2024-04-01 17:08 UTC, leonelsanchesdasilva commented on fontes/lexador/palavras-reservadas/foles.ts
> +    "canto-mais-próximo": tiposDeSimbolos.QUALITATIVO,
@VitBrandao Favor ordenar as chaves em ordem alfabética para facilitar futura manutenção.

2024-04-01 17:08 UTC, leonelsanchesdasilva commented on fontes/modificadores/atributos/posicoes.ts
> +    "lado-mais-próximo": "closest-side",
Idem.

2024-04-01 19:58 UTC, VitBrandao commented on fontes/lexador/palavras-reservadas/foles.ts
> +    "canto-mais-próximo": tiposDeSimbolos.QUALITATIVO,
@leonelsanchesdasilva pode deixar. subindo no próximo commit

2024-04-01 20:46 UTC, VitBrandao commented
@leonelsanchesdasilva Listas reorganizadas em ordem alfabética. Aproveitei o embalo e já organizei todas as palavras reservadas do lexador também.

2024-04-02 20:35 UTC, VitBrandao commented
@leonelsanchesdasilva traduzi o método `opacity()` para `opaco()` pois já existe o modificador `opacidade` e isso tava gerando problema no lexador. Se tiver uma sugestão melhor, faço a alteração.

2024-04-02 22:58 UTC, leonelsanchesdasilva requested changes

2024-04-02 22:58 UTC, leonelsanchesdasilva commented on exemplos/exemplo3.foles
> +    filtro-fundo: opaco(0.6);
@VitBrandao "opacar" existe: 

- https://dicionario.priberam.org/opacar
- https://www.dicionarioinformal.com.br/significado/opacar/3946/

2024-04-03 13:24 UTC, VitBrandao commented on exemplos/exemplo3.foles
> +    filtro-fundo: opaco(0.6);
@leonelsanchesdasilva Método renomeado para `opacar()`

2024-04-03 15:29 UTC, leonelsanchesdasilva approved these changes
Excelente trabalho. Me avise quando posso dar o merge.

2024-04-04 16:20 UTC, VitBrandao commented
@leonelsanchesdasilva finalizados os 10 métodos do grupo `filter-function-list`, **PR pronto para merge**. 
Darei sequência à resolução da Issue em uma nova branch.

2024-04-04 22:42 UTC, leonelsanchesdasilva approved these changes

2024-04-04 22:43 UTC, merged