[Issue #59] Atribuição Abreviada / Múltiplos Valores
DesignLiquido/FolEs pull request #124
Opened 2024-09-23 19:40 UTC by VitBrandao

2024-09-23 19:41 UTC, VitBrandao commented
@leonelsanchesdasilva trabalho em andamento, ainda não atingi o resultado esperado, mas estou no caminho, sigo testando e testando. Mudarei a label para `concluído` assim que finalizar.

2024-09-24 16:15 UTC, VitBrandao commented
@leonelsanchesdasilva Fiz alterações para que a nova estrutura do Avaliador Sintático siga funcionando para todos os casos de valor único - número, número-quantificador, método, qualitativo.

Ou seja, nesse momento, o Avaliador está funcionando da mesma forma que estava antes de abrir esse PR, mas com a diferença de que agora ele está estruturado para comportar múltiplos valores também, uma vez que o método `valoresModificador()` agora retorna um array.

O que está faltando ainda é implementar uma lógica que permita passar os devidos parâmetros para a classe `SeletorModificador` **quando tivermos casos de múltiplos valores/ atribuição abreviada.** 

No geral, a classe `SeletorModificador`  recebe no construtor os seguintes parâmetros:
- `nomeFolEs`
- `valor`
- `quantificador?`
- `pragmas?`

Mas agora, com o recebimento de múltiplos valores, o parâmetro `valor` está sendo diferente do que era antes. 
E também temos casos em que pode haver **mais de um** `quantificador`, como por exemplo:

`
recuo: 10px 15px 10px 15px;
`

Enfim, apenas te atualizando para saber em que pé está o PR. Sigo trabalhando. Após solucionar essas questões, acredito que a Issue esteja solucionada.

2024-09-25 20:14 UTC, leonelsanchesdasilva requested changes
Estamos no caminho certo. Além dos testes unitários, pedi algumas modificações.

2024-09-25 20:14 UTC, leonelsanchesdasilva commented on fontes/avaliador-sintatico/avaliador-sintatico.ts
> +        // IMPLEMENTAÇÃO ANTERIOR
Favor remover.

2024-09-25 20:14 UTC, leonelsanchesdasilva commented on fontes/avaliador-sintatico/avaliador-sintatico.ts
> +        while (this.simbolos[this.atual].hasOwnProperty('tipo') && this.simbolos[this.atual].tipo !== tiposDeSimbolos.PONTO_E_VIRGULA) {
```suggestion
        const simboloAtual = this.simbolos[this.atual];
        while (simboloAtual.hasOwnProperty('tipo') && simboloAtual.tipo !== tiposDeSimbolos.PONTO_E_VIRGULA) {
```

2024-09-25 20:14 UTC, leonelsanchesdasilva commented on fontes/avaliador-sintatico/avaliador-sintatico.ts
>          // TODO: Pensar num teste melhor pra isso.
Favor remover.

2024-09-25 20:14 UTC, leonelsanchesdasilva commented on fontes/avaliador-sintatico/avaliador-sintatico.ts
> +        } else {
Esse `else` não é necessário aqui. Na linha 1222, o código retorna.

2024-10-08 21:14 UTC, VitBrandao commented
Testes finalizados, PR pronto para review e merge. Issue https://github.com/DesignLiquido/FolEs/issues/59 solucionada sem comprometer o comportamento geral de FolEs

2024-10-10 16:48 UTC, leonelsanchesdasilva approved these changes
Excelente trabalho!

2024-10-10 16:50 UTC, merged