Adicionando valores de Posição aos modificadores
DesignLiquido/FolEs pull request #28
Opened 2022-12-21 17:13 UTC by VitBrandao

2022-12-21 17:16 UTC, VitBrandao commented
OBS.: PR em andamento. Darei continuidade amanhã. Seletores de Posição faltantes: **27**

2022-12-22 16:47 UTC, leonelsanchesdasilva requested changes
Está ótimo. Pedi um ajuste.

2022-12-22 16:47 UTC, leonelsanchesdasilva commented on fontes/modificadores/posicao-objeto.ts
> +const a = new PosicaoObjeto('centro');
Favor remover.

2022-12-23 19:03 UTC, leonelsanchesdasilva approved these changes

2022-12-23 19:03 UTC, merged