Criando novos modificadores da tabela MDN
DesignLiquido/FolEs pull request #3
Opened 2022-11-08 16:32 UTC by VitBrandao

2022-11-08 19:21 UTC, leonelsanchesdasilva requested changes

2022-11-08 19:21 UTC, leonelsanchesdasilva commented on fontes/modificadores/conter.ts
> +        super("conter", "contain");
`contém`

2022-11-08 19:21 UTC, leonelsanchesdasilva commented on fontes/modificadores/decoracao-caixa.ts
> +        super(["decoracao-caixa", "decoração-caixa"], "box-decoration-break");
`quebra-decoracao-caixa`

2022-11-08 19:21 UTC, leonelsanchesdasilva commented on fontes/modificadores/inserir-alinhado.ts
> +        super("inserir-alinhado", "inset-inline");
`inserção-em-linha`

2022-11-08 19:21 UTC, leonelsanchesdasilva commented on fontes/modificadores/inserir-bloco.ts
> +        super("inserir-bloco", "inset-block");
`inserção-em-bloco`

2022-11-08 19:21 UTC, leonelsanchesdasilva commented on fontes/modificadores/inserir-fim-alinhado.ts
> +        super("inserir-fim-alinhado", "inset-inline-end");
`inserção-em-linha-fim`

2022-11-08 19:21 UTC, leonelsanchesdasilva commented on fontes/modificadores/inserir-fim-bloco.ts
> +        super("inserir-fim-bloco", "inset-block-end");
`inserção-em-bloco-fim`

2022-11-08 19:21 UTC, leonelsanchesdasilva commented on fontes/modificadores/inserir-inicio-alinhado.ts
> +    nomesFoles: string[];
Precisamos disso aqui?

2022-11-08 19:21 UTC, leonelsanchesdasilva commented on fontes/modificadores/inserir-inicio-alinhado.ts
> +            "inset-inline-start"
`início-inserção-em-linha`

2022-11-08 19:21 UTC, leonelsanchesdasilva commented on fontes/modificadores/inserir-inicio-bloco.ts
> +            "inset-block-start"
`início-inserção-em-bloco`

2022-11-08 19:21 UTC, leonelsanchesdasilva commented on fontes/modificadores/inserir.ts
> +        super("inserir", "inset");
`inserção`

2022-11-08 19:21 UTC, leonelsanchesdasilva commented on fontes/modificadores/posicao-horizontal-fundo.ts
> +    nomesFoles: string[];
Precisamos disso?

2022-11-08 19:21 UTC, leonelsanchesdasilva commented on fontes/modificadores/posicao-vertical-fundo.ts
> +    nomesFoles: string[];
Idem?

2022-11-08 19:21 UTC, leonelsanchesdasilva commented on fontes/modificadores/raio-inicial-borda-final.ts
> +    nomesFoles: string[];
Idem?

2022-11-09 17:53 UTC, leonelsanchesdasilva requested changes

2022-11-09 17:53 UTC, leonelsanchesdasilva commented on fontes/modificadores/contem.ts
>      nomesFoles: string[];
Propriedades declaradas em `Modificador` não precisam ser redeclaradas aqui.

2022-11-09 17:53 UTC, leonelsanchesdasilva commented on fontes/modificadores/inicio-insercao-em-bloco.ts
>      nomesFoles: string[];
Propriedades declaradas em `Modificador` não precisam ser redeclaradas aqui.

2022-11-09 17:53 UTC, leonelsanchesdasilva commented on fontes/modificadores/inicio-insercao-em-linha.ts
>      nomesFoles: string[];
Propriedades declaradas em `Modificador` não precisam ser redeclaradas aqui.

2022-11-09 17:53 UTC, leonelsanchesdasilva commented on fontes/modificadores/insercao-em-bloco-fim.ts
> +    nomesFoles: string[];
Propriedades declaradas em `Modificador` não precisam ser redeclaradas aqui.

2022-11-09 17:53 UTC, leonelsanchesdasilva commented on fontes/modificadores/insercao-em-bloco.ts
>      nomesFoles: string[];
Propriedades declaradas em `Modificador` não precisam ser redeclaradas aqui.

2022-11-09 17:53 UTC, leonelsanchesdasilva commented on fontes/modificadores/insercao-em-linha-fim.ts
>      nomesFoles: string[];
Propriedades declaradas em `Modificador` não precisam ser redeclaradas aqui.

2022-11-09 17:53 UTC, leonelsanchesdasilva commented on fontes/modificadores/insercao-em-linha.ts
> +    nomesFoles: string[];
Propriedades declaradas em `Modificador` não precisam ser redeclaradas aqui.

2022-11-09 17:53 UTC, leonelsanchesdasilva commented on fontes/modificadores/insercao.ts
> +    nomesFoles: string[];
Propriedades declaradas em `Modificador` não precisam ser redeclaradas aqui.

2022-11-09 17:53 UTC, leonelsanchesdasilva commented on fontes/modificadores/quebra-decoracao-caixa.ts
>      nomesFoles: string[];
Propriedades declaradas em `Modificador` não precisam ser redeclaradas aqui.

2022-11-10 12:51 UTC, VitBrandao commented
Fala @leonelsanchesdasilva . 
Acabei declarando as propriedades em todos os `Modificadores` que contém `Ç` ou `acento`, mas te confesso que eu já havia me questionado se era necessário.

Vou finalizar os da MDN e depois começo a refatorar esses Modificadores, **apagando as propriedades** que já estão declaradas na superclasse. Pode ser?

2022-11-10 16:51 UTC, leonelsanchesdasilva commented
> Fala @leonelsanchesdasilva . Acabei declarando as propriedades em todos os `Modificadores` que contém `Ç` ou `acento`, mas te confesso que eu já havia me questionado se era necessário.
> 
> Vou finalizar os da MDN e depois começo a refatorar esses Modificadores, **apagando as propriedades** que já estão declaradas na superclasse. Pode ser?

@VitBrandao Ok, sem problemas.

2022-11-11 16:48 UTC, leonelsanchesdasilva approved these changes
Excelente trabalho! Parabéns!

2022-11-11 16:48 UTC, merged