[Símbolo Percentual] Refatorando Lexador
DesignLiquido/FolEs pull request #9
Opened 2022-11-21 12:23 UTC by VitBrandao

2022-11-21 16:44 UTC, leonelsanchesdasilva requested changes

2022-11-21 16:44 UTC, leonelsanchesdasilva commented on fontes/lexador/palavras-reservadas.ts
> +    "%": tiposDeSimbolos.QUANTIFICADOR,
Eu não trataria "%" como uma palavra reservada do tipo QUANTIFICADOR, até porque PERCENTUAL tem um uso especial que é sensível ao contento (por exemplo, estar depois de um número, ou no começo de uma linha).

2022-11-21 16:44 UTC, leonelsanchesdasilva commented on package.json
> +    ],
Não esqueça do link do LinkedIn aqui (veja o `package.json` de Delégua.

2022-11-22 14:09 UTC, VitBrandao commented
**Update**: Símbolo % já tratado no Lexador e funcionando de acordo. Erro agora passou para o Avaliador Sintático.

**Status atual do PR**: Estudando estrutura do Avaliador para tratar os casos em que **% é do tipo Percentual**. Para os casos em que é tipado como **Quantificador**, a lógica já está de acordo.

2022-11-22 16:54 UTC, leonelsanchesdasilva approved these changes
Muito bom!

2022-11-22 16:54 UTC, leonelsanchesdasilva commented
@VitBrandao Não esqueça de fazer merge com `principal`.

2022-11-22 17:57 UTC, merged